name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.3.1
  mockito: ^5.3.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  http_mock_adapter: ^0.6.1
