// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETfX8XDGAJBdBzkRZY68vBBeIYO0HWT0',
    appId: '1:604875622337:web:5320b41d2a792603439140',
    messagingSenderId: '604875622337',
    projectId: 'recipe-app-exam',
    authDomain: 'recipe-app-exam.firebaseapp.com',
    databaseURL: 'https://recipe-app-exam-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-exam.appspot.com',
    measurementId: 'G-ZG057KKBY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQVnVCmbeOV5S0HSauuOVEyeGNh0n814',
    appId: '1:604875622337:android:57cf5246e4fc90ee439140',
    messagingSenderId: '604875622337',
    projectId: 'recipe-app-exam',
    databaseURL: 'https://recipe-app-exam-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDthmQNH7ilcYJfPnAqBz-52vuWTQbpAjM',
    appId: '1:604875622337:ios:2a5cad034118de73439140',
    messagingSenderId: '604875622337',
    projectId: 'recipe-app-exam',
    databaseURL: 'https://recipe-app-exam-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-exam.appspot.com',
    iosBundleId: 'com.example.receipeApp',
  );
}
